version: "3"
services:
  db:
    image: boccifarm/mysql:8.0.23
    build:
      context: ./docker/db/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
  app:
    image: boccifarm/rails:6.1.3-ruby3.0.0-alpine3.13
    build:
      context: ./app/
      dockerfile: ../docker/app/Dockerfile
    environment:
      RAILS_DATABASE_HOST: db
      RAILS_DATABASE_USERNAME: root
      RAILS_DATABASE_PASSWORD: password
    ports:
      - 3000:3000
    depends_on:
      - db
  web:
    image: boccifarm/nginx:1.18.0-alpine
    build:
      context: ./docker/web/
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  db:
