apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: RAILS_DATABASE_HOST
              value: db
            - name: RAILS_DATABASE_PASSWORD
              value: password
            - name: RAILS_DATABASE_USERNAME
              value: root
          image: boccifarm/rails:6.1.3-ruby3.0.0-alpine3.13
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
